steps:
  - name: gcr.io/cloud-builders/docker
    id: BUILD
    entrypoint: "bash"
    args:
      - -c
      - |
        docker build --build-arg DB="$$DB_URL" --build-arg SENTRY="$$SENTRY" -t $_SERVICE_IMAGE .
    secretEnv: ["DB_URL", "SENTRY"]

  - name: gcr.io/cloud-builders/docker
    id: PUSH
    args: ["push", "$_SERVICE_IMAGE"]

  - name: gcr.io/cloud-builders/gcloud
    id: DEPLOY
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --project=$PROJECT_ID
      - --region=$_SERVICE_REGION
      - --image=$_SERVICE_IMAGE

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/prod_db_url/versions/latest
      env: "DB_URL"
    - versionName: projects/$PROJECT_ID/secrets/sentry_auth_token/versions/latest
      env: "SENTRY"

images:
  - $_SERVICE_IMAGE

substitutions:
  _SERVICE_IMAGE: ${_SERVICE_REGION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REGISTRY}/${_DOCKER_IMAGENAME}:${SHORT_SHA}
  _SERVICE_REGION: asia-northeast3
  _SERVICE_NAME: api-prod-service
  _DOCKER_REGISTRY: api-prod-repo
  _DOCKER_IMAGENAME: api
